### PR TITLE
Add support for Rmarkdown file formats

### PR DESCRIPTION
**Pull request by cenksoykan**
Although Rmarkdown have same syntax with markdown, due to some plugins ```:set ft=markdown``` does not work for ```.Rmd``` files. Also vim supports rmd as a filetype and syntax. Therefore I duplicated markdown filter for rmarkdown support

### CODE REVIEW

**Comment by tacahiroy** [comment]
Thanks for the PR.
It would be good just to return the result of `ctrlp#funky#ft#markdown#filters()` if it's the same pattern as markdown' :)

**Comment by cenksoykan** [comment]
It was my very first attempt then it cause an error like this
```
E746: Function name does not match script file name: ctrlp#funky#ft#markdown#filters
```
Of course you can change/keep author name as yours totally fine and deserved :+1:  sorry about I typed mine
Thanks :)

**Comment by tacahiroy** [comment]
appreciate your contribution:)

What I meant is like this:
https://github.com/tacahiroy/ctrlp-funky/blob/master/autoload/ctrlp/funky/ft/sh.vim#L28

Calling the filter function of markdown inside of the *rmarkdown* filter function.

**Comment by cenksoykan** [comment]
Aaah I see. And it must be rmd not rmarkdown because a plugin that I use changes behavior. I unplugged vim-rmarkdown plugin then realized it sets filetype as rmarkdown instead rmd

**Comment by cenksoykan** [comment]
Is there any way figure out pattern for **horizontal rule** is not a heading.
```
---
```
This pattern alone recognized as empty headline when it was only horizontal line
And also using **yaml header** at the beginning...

**Comment by tacahiroy** [comment]
Ah, that should be a bug for the markdown filter.
I'll take a look.

**Comment by tacahiroy** [comment]
The horizontal rule problem has been fixed with: 4f5aae86

**Comment by tacahiroy** [comment]
Thanks for your contribution!

**Pull request merged**
